[target.thumbv6m-none-eabi]
# Choose a default "cargo run" tool:
# - probe-run provides flashing and defmt via a hardware debugger
runner = "probe-run --chip RP2040"
# - elf2uf2-rs loads firmware over USB when the rp2040 is in boot mode
# runner = "elf2uf2-rs -d"

rustflags = [
  "-C", "linker=flip-link", # comment out when using elf2uf2-rs runner
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x", # comment out when using elf2uf2-rs runner
  "-C", "inline-threshold=5",
  "-C", "no-vectorize-loops",
]

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"
