name: cargo build

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: add thumbv6m-none-eabi target
              run: rustup target add thumbv6m-none-eabi
            - name: Build
              run: cargo build --verbose
