name: check and build

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: add thumbv6m-none-eabi target
              run: rustup target add thumbv6m-none-eabi
            - name: install deps
              run: cargo install flip-link
            - name: Check formatting
              run: cargo fmt --check
            - name: Check examples
              run: cargo check --examples
            - name: Build examples
              run: cargo build --examples
